language: cpp

# from <http://stackoverflow.com/questions/22111549/travis-ci-with-clang-3-4-and-c11>

compiler:
  - clang
  - gcc

before_install:
  # g++-6
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq

  # g++6
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-6; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6"; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

  # for OpenPGP
  - sudo apt-get install libgmp-dev
  - sudo apt-get install libbz2-dev
  - sudo apt-get install zlib1g-dev
  - sudo apt-get install libzip-dev

  # for Google Test
  - sudo apt-get install git cmake

before_script:
  # not much better than git submodules, but there was never a need/want for the repo in this repo
  - cd ..
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - git reset --hard d62d6c6556d96dda924382547c54a4b3afedb22c
  - cmake CMakeLists.txt
  - make

  - cd ../OpenPGP/tests
  - make

script:
  - ./tests
